import { prisma } from '@/lib/prisma'
import Badge from '@/components/ui/Badge'
import { formatDate, formatNumber } from '@/lib/format'

const statusLabel = { DRAFT: 'مسودة', UNDER_REVIEW: 'قيد المراجعة', QUOTED: 'تم التسعير', ACCEPTED: 'مقبول', REJECTED: 'مرفوض', COMPLETED: 'مكتمل' }

export default async function ServiceRequestsPage() {
  const requests = await prisma.partnerServiceRequest.findMany({ include: { buyer: { select: { name: true, email: true } }, items: { include: { service: true } } }, orderBy: { createdAt: 'desc' } }).catch(() => [])
  return <div className="dashboard-page"><header className="page-hero mb-6 p-6"><p className="mb-2 text-xs font-bold text-[#B99A63]">خدمات الشركاء</p><h1 className="text-2xl font-extrabold text-white">طلبات الخدمات الإضافية</h1><p className="mt-2 text-sm text-white/65">مراجعة الطلبات والأسعار التقديرية من دون أي خطوة دفع.</p></header><div className="space-y-4">{requests.length === 0 ? <div className="premium-card p-12 text-center text-[#5F6764]">لا توجد طلبات خدمات</div> : requests.map((request) => <article key={request.id} className="premium-card p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p dir="ltr" className="text-right text-xs font-bold text-[#B99A63]">{request.publicRef}</p><h2 className="mt-1 font-extrabold text-[#1B1B1B]">{request.buyer.name}</h2><p className="mt-1 text-xs text-[#5F6764]">{formatDate(request.createdAt)} · {request.buyer.email}</p></div><Badge variant={request.status === 'UNDER_REVIEW' ? 'warning' : request.status === 'COMPLETED' ? 'success' : 'gray'}>{statusLabel[request.status]}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{request.items.map((item) => <span key={item.id} className="rounded-full bg-[#F5F1E8] px-3 py-1.5 text-xs font-bold text-[#33423F]">{item.service.name} × {formatNumber(item.quantity)}</span>)}</div>{request.notes && <p className="mt-4 text-sm leading-7 text-[#3F4B47]">{request.notes}</p>}<p className="mt-4 text-xs font-bold text-[#B99A63]">الإجمالي التقديري: {formatNumber(request.estimatedTotal)} ر.س</p></article>)}</div></div>
}
